l_english:
 SETTINGS_PAGE_GRAPHICS: "グラフィック"
 SETTINGS_PAGE_GAME: "ゲーム"
 SETTINGS_PAGE_SYSTEM: "システム"
 SETTINGS_PAGE_CONTROLS: "操作"
 SETTINGS_PAGE_EDITOR: "エディタ"
 SETTINGS_PAGE_INTERFACE: "インターフェース"
 SETTINGS_PAGE_AUDIO: "オーディオ"
 SETTINGS_CATEGORY_SCREEN: "スクリーン"
 SETTINGS_CATEGORY_QUALITY: "品質"
 OPTION_EASY: "簡単"
 OPTION_NORMAL: "標準"
 OPTION_HARD: "ハード"
 OPTION_NEVER: "なし"
 OPTION_MONTHLY: "毎月"
 OPTION_HALFYEAR: "半年に1度"
 OPTION_YEARLY: "毎年"
 OPTION_FIVE_YEAR: "5年に1度"
 OPTION_NO_AUTOSAVE: "オートセーブしない"
 SETTINGS_CATEGORY_ACCOUNT: "アカウント"
 SETTINGS_CATEGORY_SYSTEM: "システム"
 SETTINGS_CATEGORY_CONTROLS: "コントロール"
 SETTINGS_CATEGORY_CAMERA: "カメラ"
 SETTINGS_CATEGORY_AUDIO: "オーディオ"
 SETTINGS_CATEGORY_GUI: "GUI"
 RESTORE: "戻す"
 SAVE_AND_CLOSE: "OK"
 SETTINGS: "設定"
 REQUIRES_RESTART: "再起動が必要"
 REQUIRE_RESTART_DESCRIPTION: "いくつかの設定はゲームをリスタートするまで有効になりません。"
