l_english:
 SETTING_RENDERER: "レンダラー"
 SETTING_VSYNC: "垂直同期"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!ゲームのフレームレートをモニタのリフレッシュレートと同期させ、ティアリングを減少させます。\n\n無効化によりパフォーマンスの向上が見込めます。"
 SETTING_MULTI_SAMPLING: "アンチエイリアス（MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!マルチサンプルアンチエイリアス（MSAA)を有効にすると画像の縁が滑らかになります。\n\n低い設定にするとパフォーマンスの向上が見込めます。"
 SETTING_ANISOTROPIC_FILTERING: "テクスチャフィルタリング"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!異方性フィルタリングを使用するとテクスチャ表面の見栄えが良くなります。\n\n低い設定にするとパフォーマンスの向上が見込めます。"
 SETTING_FULLSCREEN_RESOLUTION: "解像度"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!ゲームの画像品質を設定します。\n\n低い解像度に設定するとパフォーマンスの向上が見込めます。"
 SETTING_WINDOWED_RESOLUTION: "ウィンドウ化時の解像度"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "ゲームの解像度です。高い解像度にするほど高い負荷がかかります。"
 SETTING_DISPLAY: "モニタ"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!複数のモニタをコンピュータで使用している場合に、ゲームに用いるものを選択します。"
 SETTING_GRAPHICS_DEVICE: "グラフィックカード"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!ゲームに使用するグラフィックカードを選択します。\n\n統合グラフィックカードやソフトウェアによるレンダラを使用するとパフォーマンスが低下する可能性があります。"
 SETTING_SHADOW_MAP_RESOLUTION: "影の品質"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!影の表示が有効になっている際の、地図に描画される影の解像度を決定します。\n\n低い設定にするとパフォーマンスの向上が見込めます。"
 SETTING_DISPLAY_MODE: "ディスプレイモード"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!ゲームを画面に表示する方法を決定します。"
 SETTING_BLOOM: "ブルーム効果"
 SETTING_MESH_LOD_BIAS: "メッシュにかけるLODの品質"
 SETTING_MESH_LOD_FADE: "メッシュにかけるLODフェード"
 OPTION_FULLSCREEN: "フルスクリーン"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!ゲームをスクリーン全体に表示します。解像度の設定によって画像の鮮明さが変化します。"
 OPTION_WINDOWED: "ウィンドウ"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!ゲームをウインドウに表示します。解像度設定はウインドウサイズを変化させます。"
 OPTION_OFF: "オフ"
 OPTION_LOW: "低"
 OPTION_MEDIUM: "中"
 OPTION_HIGH: "高"
 OPTION_CUSTOM: "カスタム"
 SETTINGS_CATEGORY_UI:0 "インターフェース"
 SETTINGS_CATEGORY_GAME:0 "ゲーム"
 SETTING_QUALITY:0 "プリセット"
 SETTING_SFX:0 "SFX（特殊効果）"
 SETTING_UI:0 "インターフェース"
 SETTING_QUALITY_TOOLTIP:0 "#T $SETTING_QUALITY$\n#!プリセットを選択することで、以下に表示されている高度なグラフィックオプションを設定します。\n\n低い設定のプリセットを使用するとパフォーマンスの向上が見込めます。"
 SETTING_BLOOM_TOOLTIP:0 "#T $SETTING_BLOOM$\n#!ブルーム効果を有効にします。非常に明るい部分の光が画像の他の部分に広がる効果が発生します。\n\n無効化によりパフォーマンスの向上が見込めます。"
 SETTING_REFRACTION_TOOLTIP:0 "屈折が水面に現れるかどうかを決定します。"
 SETTING_REFRACTION_QUALITY_TOOLTIP:0 "#T $SETTING_REFRACTION_QUALITY$#!\n水の反射が有効になっている場合に、その品質を制御します。\n\n低い設定にするとパフォーマンスの向上が見込めます。"
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nマップオブジェクト（建造物など）がとれる最高品質を決定します。\n\n低い設定にするとパフォーマンスの向上が見込めます。"
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nユニットモデルなどのマップ上のオブジェクトにかけるLOD（Levels of detail）の品質を決定します。\n\n低い設定にするとパフォーマンスの向上が見込めます。"
 SETTING_MESH_LOD_FADE_TOOLTIP:0 "#T $SETTING_MESH_LOD_FADE$\n#!有効にすると、ズームインもしくはズームアウトしたときに異なったLOD（Levels of detail）間で3Dモデルが滑らかに移り変わります。\n\n無効化によりパフォーマンスの向上が見込めます。"
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "区域や州の名前をマップ上に表記するかを決定します。"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "マップ上に表示される国境に通行不可能な地形を含めるかどうかを決定します。"
 SETTING_LANGUAGE_TOOLTIP:0 "#T $SETTING_LANGUAGE$#!\nユーザーインタフェースの言語を決定します。"
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "あなたのParadoxアカウントのEメール"
 SETTING_ANIMATION_SPEED: "アニメーション速度"
 SETTING_GUI_SCALING: "GUIスケーリング"
 SETTING_GUI_SCALING_TOOLTIP:0 "#T $SETTING_GUI_SCALING$\n#!全体的なユーザーインターフェースのスケールを設定します。より大きな画面解像度を使用する際に役立ちます。\n\n#X この値を高くしすぎるとインターフェースが正常にスクリーンに収まらなくなります！#!"
 SETTING_MOUSE_PANNING: "エッジスクローリング"
 SETTING_SCROLL_SPEED: "画面スクロール速度"
 SETTING_CAMERA_ROTATION_SPEED: "カメラの回転速度"
 SETTING_ZOOM_SPEED: "ズーム速度"
 SETTING_INPUT_DEVICE: "入力デバイス"
 SETTING_EDITOR: "エディター"
 SETTING_EDITOR_POSTFIX: "ポストフィックス"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "エディタを開くコマンド"
 SETTING_GRACEFUL_EXIT: "正常終了"
 SETTING_LANGUAGE: "言語"
 MOUSE_AND_KEYBOARD: "マウスとキーボード"
 GAMEPAD: "ゲームパッド"
 SETTING_MULTISAMPLING_DISABLED: "無効"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "無効"
 SETTING_CAMERA_TILT: "カメラチルト"
 SETTING_CAMERA_STRATEGY: "カメラタイプ"
 SETTING_CENTERED_ZOOM_IN: "中心にズームイン"
 SETTING_CAMERA_SPEED: "カメラ速度"
 CAMERA_TABLETOP: "テーブルトップ"
 CAMERA_FPS: "一人称視点"
 CAMERA_WASD: "WASD方式"
 SETTING_Music: "ミュージック"
 SETTING_Ambient: "環境音"
 SETTING_Effects: "エフェクト音"
 SETTING_Master: "マスター"
 SETTING_Master_TOOLTIP:0 "#T マスターボリューム\n#!ゲーム内の全体的な音量を設定します。"
 SETTING_Music_TOOLTIP:0 "#T ミュージックボリューム\n#!音楽のボリュームを設定します。"
 SETTING_Ambient_TOOLTIP:0 "#T 環境音ボリューム\n#!環境音の音量を制御します。"
 SETTING_SFX_TOOLTIP:0 "#T SFXボリューム\n#!戦闘などのサウンドエフェクトのボリュームを制御します。"
 SETTING_UI_TOOLTIP:0 "#T インターフェースボリューム\n#!ユーザーインターフェースのボリュームを設定します。"
 SETTING_AUTOSAVE_TOOLTIP:0 "#T $SETTING_AUTOSAVE$\n#!オートセーブの頻度を設定します。"
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "オートセーブデータをクラウドに保存するかどうかを設定します。"
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "カメラが常に北を向くかどうかを設定します。"
 NO_AUTOSAVE:0 "オートセーブなし"
 SETTING_MOUSE_PANNING_TOOLTIP:0 "#T $SETTING_MOUSE_PANNING$\n#!マウスカーソルがスクリーンもしくはウインドウの端にあるときにマップをスクロールするかどうかを設定します。"
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$秒"
 OPTION_DISABLED: "無効"
 OPTION_DEFAULT: "デフォルト"
 SETTING_TERRAIN_SMOOTHING: "地形のスムージング"
 OPTION_ULTRA: "極限"
 SETTING_TEXTURE_QUALITY:0 "テクスチャの品質"
 SETTING_TEXTURE_QUALITY_TOOLTIP:0 "#T $SETTING_TEXTURE_QUALITY$#!\n読み込まれるテクスチャの解像度を制御します。\n\n低い設定にするとパフォーマンスの向上が見込めます。"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "ログコマンドを参照"
 SETTING_ANTI_ALIASING:0 "アンチエイリアス"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!アンチエイリアスを有効にすると画像の縁が滑らかになります。\n\nFXAAがお薦めです。"
 OPTION_ANTI_ALIASING_DISABLED:0 "無効"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_FRAMERATE_CAP:1 "最大FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nゲームのレンダリングにおける最大FPS（フレーム毎秒）。\n\n低い設定にすると消費電力の低下が見込めます。"
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "デバッグログのレベル"
